### ISSUE TITLE
node and npm

### ISSUE THREAD

**Issue by poing** [poing/laravel-elb#7]
Need to adjust, move away from the `epel`.
Keeping the original for backwards compatibility.

```yml
commands:
  01-install-node-old:
    command: "yum install nodejs npm --enablerepo=epel -y || :"
    ignoreErrors: true
  01-install-node-new:
    command: "yum install nodejs npm -y || :"
    ignoreErrors: true
```
